site_name: Pylnbits Docs

theme:
  name: "readthedocs"
  highlightjs: true
  hljs_languages:
    - yaml
    - python


repo_url: https://github.com/lightningames/pylnbits
edit_uri: https://github.com/lightningames/pylnbits/blob/main/docs/index.md

site_author: bitkarrot

plugins:
  - mkdocstrings
  - search

nav:
  - Pylnbits Docs: index.md
  - How-To guides: how-to-guides.md
  - Reference: reference.md
  - Explanation: explanation.md
